### ISSUE TITLE
Seqvars Effects Filters missing fields 

### ISSUE THREAD

**Issue by Gregoor** [varfish-org/varfish-server#1835] opened 2024-07-24 12:17 UTC
all the commented out entries are present in the design, but missing in the API. Manuel confirmed that these are still WIP.

Most of them seem to be present here:
https://github.com/varfish-org/varfish-server/blob/8d39e44c3d0d0265d353a5f4f17b52fd175755c8/backend/seqvars/models.py#L109-L208
            
<img width="183" alt="Screenshot 2024-07-24 at 14 17 42" src="https://github.com/user-attachments/assets/91830a42-3fa5-4d64-843a-56342c1e184b">

Effect groups I also could not find in the API yet

**Comment by holtgrewe** [comment] 2024-10-10 09:02
duplicate of #1834

**Closed by holtgrewe** 2024-10-10 09:02 UTC
